apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o7r2s0qlt-dotnet-basic
  janus-idp.io/tekton: o7r2s0qlt-dotnet-basic
  backstage.io/kubernetes-id: o7r2s0qlt-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o7r2s0qlt-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
